spring:
# Connection Details
  data:
    mongodb:
      host: localhost
      port: 27017
      database: formpilot_activity_db

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        bindings:
          activity-out-0:
            destination: fitness-topic
            content-type: application/json

# RabbitMQ configurations
#      bindings:
#        activity-out-0:
#          destination: fitness.exchange
#          content-type: application/json
#      rabbit:
#        bindings:
#          activity-out-0:
#            producer:
#              routing-key-expression: "'activity.tracking'"



server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracking