spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: formpilot_ai_db

  cloud:
    function:
      definition: activityProcessor
    stream:
      bindings:
        activityProcessor-in-0:
          destination: fitness.exchange
          group: ai-service-group
          content-type: application/json
      rabbit:
        bindings:
          activityProcessor-in-0:
            consumer:
              binding-routing-key: activity.tracking

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}