spring:
  application:
    name: activity-service

# Connection Details
  data:
    mongodb:
      host: localhost
      port: 27017
      database: formpilot_activity_db

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/